routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/','WelcomeController@index');
Route::get('/single/{id}','SingleController@show');
Route::get('/cat/{id}','PagesController@show');

//Route::get('/single', function () {
//    return view('pages.single');
//});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/home', 'HomeController@index')->name('home');

// manage category
Route::get('published-category/{id}','CategoriesController@publish_category');
Route::get('unpublished-category/{id}','CategoriesController@unpublish_category');
Route::resource('category','CategoriesController');

// manage slider
Route::get('published-slider/{id}','SlidersController@publish_slider');
Route::get('unpublished-slider/{id}','SlidersController@unpublish_slider');
Route::resource('slider','SlidersController');

// manage category
Route::get('published-product/{id}','ProductsController@publish_product');
Route::get('unpublished-product/{id}','ProductsController@unpublish_product');
Route::resource('product','ProductsController');
// manage location
Route::get('published-location/{id}','LocationsController@publish_location');
Route::get('unpublished-location/{id}','LocationsController@unpublish_location');
Route::resource('location','LocationsController');
Route::resource('seller','SellersController');

resources/views/admin/main-content.blade.php
@extends('admin.master')
@section('main-content')

        <div class="panel">
            <h2>WELCOME PICKPOINT DASHBOARD</h2>
        </div>

@endsection

resources/views/admin/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Pickpoint</title>

    <!-- Styles -->
    <link href="{{ asset('css/admin_custom.css') }}" rel="stylesheet">

</head>
<body>
<nav class="navbar navbar-default">
    <a class="navbar-brand" href="{{ url('/home') }}">
        PickPoint
    </a>
    {{--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">--}}
        {{--<span class="navbar-toggler-icon"></span>--}}
    {{--</button>--}}
    <div class="collapse navbar-collapse" id="navbarNavDropdown">



            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @if (Auth::guest())
                    <li><a href="{{ route('login') }}">Login</a></li>
                    <li><a href="{{ route('register') }}">Register</a></li>
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endif
            </ul>

    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            <div class="left-menu">
                <ul>
                    <li><a href="{{route('category.index')}}">Category</a></li>
                    <li><a href="{{route('slider.index')}}">Slider</a></li>
                    <li><a href="{{route('product.index')}}">Product</a></li>
                    <li><a href="{{route('seller.index')}}">Seller</a></li>
                    <li><a href="{{route('location.index')}}">Location</a></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-10">
            @yield('main-content')
        </div>
    </div>
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>