routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/','WelcomeController@index');
Route::get('/single/{id}','SingleController@show');
Route::get('/cat/{id}','PagesController@show');

//Route::get('/single', function () {
//    return view('pages.single');
//});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/home', 'HomeController@index')->name('home');

// manage category
Route::get('published-category/{id}','CategoriesController@publish_category');
Route::get('unpublished-category/{id}','CategoriesController@unpublish_category');
Route::resource('category','CategoriesController');

// manage slider
Route::get('published-slider/{id}','SlidersController@publish_slider');
Route::get('unpublished-slider/{id}','SlidersController@unpublish_slider');
Route::resource('slider','SlidersController');

// manage category
Route::get('published-product/{id}','ProductsController@publish_product');
Route::get('unpublished-product/{id}','ProductsController@unpublish_product');
Route::resource('product','ProductsController');
// manage location
Route::get('published-location/{id}','LocationsController@publish_location');
Route::get('unpublished-location/{id}','LocationsController@unpublish_location');
Route::resource('location','LocationsController');
Route::resource('seller','SellersController');

app/Location.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    public function seller()
    {
        return $this->hasOne('App\Seller');
    }
}

app/Http/Controllers/LocationsController.php
<?php

namespace App\Http\Controllers;

use App\Location;
use App\Seller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class LocationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public  function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $locations = Location::all();
        return view('locations.index')->withLocations($locations);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sellers = Seller::all();
        return view('locations.create')->withSellers($sellers);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'address' => 'required',
            'publication_status' => 'required'

        ]);

        $location = new Location();
        $location->address = $request->address;
        $location->publication_status = $request->publication_status;
        $location->save();
        Session::flash('message', 'Location Insert Successfully');
        return redirect()->route('location.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $location = Location::findOrFail($id);
        return view('locations.edit')
            ->withLocation($location);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'address' => 'required',
            'publication_status' => 'required',

        ]);

        $location = Location::findOrFail($id);
        $location->address = $request->address;
        $location->publication_status = $request->publication_status;
        $location->update();

        Session::flash('message', 'Location Update Successfully');
        return redirect()->route('location.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $location = Location::findOrFail($id);
        $location->delete();
        Session::flash('message', 'Location Delete Successfully');
        return redirect()->route('location.index');
    }


    public function publish_location($id)
    {
        $location=Location::where('id',$id)->update(['publication_status'=>1]);
        return redirect()->route('location.index')->withSlider($location);
    }

    public function unpublish_location($id)
    {
        $location=Location::where('id',$id)->update(['publication_status'=>0]);
        return redirect()->route('location.index')->withSlider($location);
    }
}

resources/views/locations/create.blade.php
@extends('admin.master')
@section('main-content')
    @if(Session::get('message'))
        <div class="alert alert-success">
            <h4>{{Session::get('message')}}</h4>
        </div>
    @endif
    @if($errors->all())
        <div class="alert alert-danger">
            <ul>
                @foreach($errors as $error)
                    <li>{{$error->error}}</li>
                @endforeach
            </ul>
        </div>

    @endif
    <div class="well">
        <h3>Create Location</h3>

        <form action="{{route('location.store')}}" method="post">
            {{csrf_field()}}
            <div class="form-group">
                <label for="address">Address</label>
                <textarea name="address" id="address" cols="30" rows="10" class="form-control"></textarea>

            </div>

            <label for="publication_status">Publication Status:</label>
            <select name="publication_status" id="" class="form-control">
                <option value="1">Publish</option>
                <option value="0">Un Publish</option>
            </select>
            <br>
            <input type="submit" value="Save" class="btn btn-success">
        </form>
    </div>
@endsection

resources/views/locations/edit.blade.php
@extends('admin.master')
@section('main-content')
    <div class="panel panel-default">

        <div class="panel-heading"><i class="fa fa-laptop"> EDIT LOCATION </i></div>
        @if($errors->all())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors as $error)
                        <li>{{$error->error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if(Session::get('message'))
            <div class="alert alert-success">
                <h4>{{Session::get('message')}}</h4>
            </div>
        @endif
        <div class="panel-body">
        {!! Form::model($location,['route'=>['location.update',$location->id],'method' => 'patch']) !!}
        <!-- Title Form Input -->
            <div class="form-group">
                {{Form::label('address','Address:')}}
                {{Form::textarea('address',null,['class'=>'form-control'])}}
            </div>

        <div class="form-group">
            {{ Form::select('publication_status', ['1' => 'Publish', '0' => 'Un Publish'], null, ['placeholder'=>'select status', 'class' => 'form-control'])}}

        </div>

        {{Form::submit('update',['class'=>'btn btn-success btn-sm pull-left','style'=>'margin-right:5px'])}}
        {!! Form::close() !!}
        <a href="{{route('location.index')}}" class="fa fa-arrow-left btn btn-info btn-sm pull-left"> back</a>
        {!! Form::open(['route'=>['location.destroy',$location->id],'method'=>'DELETE']) !!}
        {{  Form::button( '<i class="fa fa-trash-o">delete</i>', ['type' => 'submit','class'=>'btn btn-danger btn-sm btn-delete','style'=>'margin:0 5px;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
        {!! Form::close() !!}
        </div><!-- panel-body -->
    </div><!-- panel panel-default -->

@endsection

resources/views/locations/index.blade.php
@extends('admin.master')
@section('main-content')

        <div class="well">
            <h3><a href="{{route('location.create')}}">ADD NEW + </a>LOCATION</h3>

            <form action="{{route('location.index')}}" method="get" class="pull-right form-inline">
                <div class="form-group">
                    <input type="text" role="search" class="form-control">
                    <input type="submit" value="search" class="btn btn-info">
                </div>
            </form>

            <table class="table">
                <thead>
                <tr>
                    <th>SL</th>
                    <th>ADDRESS</th>
                    <th>PUBLICATION STATUS</th>
                    <th>ACTION</th>
                </tr>
                </thead>
                <tbody>
                @php($sl=1)
                @foreach($locations as $location)
                    <tr>
                        <td>{{$sl++}}</td>
                        <td>{{$location['address']}}</td>
                        <td>
                            @if($location->publication_status==1)
                                <span class="fa fa-thumbs-o-up text-success">publish</span>
                            @else
                                <span class="fa fa-thumbs-o-down text-danger">un publish</span>
                            @endif

                        </td>
                        <td>
                            @if($location->publication_status==1)
                                <a class="btn btn-success" href="{{asset('unpublished-location/'.$location->id)}}"
                                   style="float: left;margin-right: 3px;">
                                    <i class="glyphicon glyphicon-thumbs-down"></i>
                                </a>
                            @else
                                <a class="btn btn-danger" href="{{asset('published-location/'.$location->id)}}"
                                   style="float: left;margin-right: 3px;">
                                    <i class="glyphicon glyphicon-thumbs-up"></i>
                                </a>
                            @endif
                            {!! Html::decode(Html::linkRoute('location.show','<i class="fa fa-eye">view</i>', [$location->id],['style'=>'margin:5px; float:left'])) !!}
                            {!! Html::decode(Html::linkRoute('location.edit','<i class="fa fa-pencil-square-o">edit</i>', [$location->id],['style'=>'margin:5px; float:left'])) !!}
                            {!! Form::open(['route'=>['location.destroy',$location->id],'method'=>'DELETE']) !!}
                            {{  Form::button( '<i class="fa fa-trash-o"></i>', ['type' => 'submit','style'=>'margin:0;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
                            {!! Form::close() !!}
                        </td>

                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>


@endsection