routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/','WelcomeController@index');
Route::get('/single/{id}','SingleController@show');
Route::get('/cat/{id}','PagesController@show');

//Route::get('/single', function () {
//    return view('pages.single');
//});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/home', 'HomeController@index')->name('home');

// manage category
Route::get('published-category/{id}','CategoriesController@publish_category');
Route::get('unpublished-category/{id}','CategoriesController@unpublish_category');
Route::resource('category','CategoriesController');

// manage slider
Route::get('published-slider/{id}','SlidersController@publish_slider');
Route::get('unpublished-slider/{id}','SlidersController@unpublish_slider');
Route::resource('slider','SlidersController');

// manage category
Route::get('published-product/{id}','ProductsController@publish_product');
Route::get('unpublished-product/{id}','ProductsController@unpublish_product');
Route::resource('product','ProductsController');
// manage location
Route::get('published-location/{id}','LocationsController@publish_location');
Route::get('unpublished-location/{id}','LocationsController@unpublish_location');
Route::resource('location','LocationsController');
Route::resource('seller','SellersController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function products(){
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     *
     */
    public  function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $categories = Category::all();
        return view('categories.index')->withCategories($categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request,[
           'name'=>'required | min:2 | max:20',
            'publication_status'=>'required'
        ]);

        $category = new Category();
        $category->name=$request->name;
        $category->publication_status=$request->publication_status;
        $category->save();

        return redirect()->route('category.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category= Category::findOrFail($id);
        return view('categories.edit')->withCategory($category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required | min:2 | max:20',
            'publication_status'=>'required'
        ]);

        $category= Category::findOrFail($id);
        $category->name=$request->name;
        $category->publication_status=$request->publication_status;
        $category->update();

        Session::flash('message','Data update Successfull');

        return redirect()->route('category.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function publish_category($id)
    {
        $category=Category::where('id',$id)->update(['publication_status'=>1]);
        return redirect()->route('category.index')->withCategory($category);
    }

    public function unpublish_category($id)
    {
        $category=Category::where('id',$id)->update(['publication_status'=>0]);
        return redirect()->route('category.index')->withCategory($category);
    }



    public function destroy($id)
    {
        $category= Category::findOrFail($id);
        $category->delete();
        return redirect()->route('category.index');
    }
}

resources/views/categories/create.blade.php
@extends('admin.master')
@section('main-content')
    <div class="well">
        @if(Session::get('success'))
            <div class="alert alert-success">
                <h4>{{Session::get('success')}}</h4>
            </div>
        @endif
    <h3>Create Category</h3>

    <form action="{{route('category.store')}}" method="post">
        {{csrf_field()}}
        <div class="form-group">
            <label for="name">Category Name</label>
            <input type="text" name="name" class="form-control">
        </div>
        <select name="publication_status" id="" class="form-control">
            <option value="1">Publish</option>
            <option value="0">Un Publish</option>
        </select>
        <br>
        <input type="submit" value="Save" class="btn btn-success">
    </form>

    @endsection
    </div>

resources/views/categories/edit.blade.php
@extends('admin.master')
@section('main-content')
    <div class="panel panel-default">

        <div class="panel-heading"><i class="fa fa-laptop"> EDIT CATEGORY </i></div>

        <div class="panel-body">
        {!! Form::model($category,['route'=>['category.update',$category->id],'method' => 'patch']) !!}
        <!-- Title Form Input -->
            <div class="form-group">
                {{Form::label('name','Name:')}}
                {{Form::text('name',null,['class'=>'form-control'])}}
            </div>


            <!-- Publication_status Form Input -->
            <div class="form-group">
                {{ Form::select('publication_status', ['1' => 'Publish', '0' => 'Un Publish'], null, ['placeholder'=>'select status', 'class' => 'form-control'])}}

            </div>
            {{Form::submit('update',['class'=>'btn btn-success btn-sm'])}}
            {!! Form::close() !!}
            <a href="{{route('category.index')}}" class="fa fa-arrow-left btn btn-info btn-sm"> back</a>
            {!! Form::open(['route'=>['category.destroy',$category->id],'method'=>'DELETE']) !!}
            {{  Form::button( '<i class="fa fa-trash-o">delete</i>', ['type' => 'submit','class'=>'btn btn-danger btn-sm','style'=>'margin:0;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('admin.master')
@section('main-content')
    <div class="col-sm-10">
        <div class="well">
            <h3><a href="{{route('category.create')}}">ADD NEW + </a>CATEGORIES</h3>

            <form action="{{route('category.index')}}" method="get" class="pull-right form-inline" >
                <div class="form-group">
                    <input type="text" role="search" class="form-control">
                    <input type="submit" value="search" class="btn btn-info">
                </div>
            </form>

            <table class="table">
                <thead>
                <tr>
                    <th>SL</th>
                    <th>NAME</th>
                    <th>PUBLICATION STATUS</th>
                    <th>ACTION</th>
                </tr>
                </thead>
                <tbody>
                @php($sl=1)
                @foreach($categories as $category)
                    <tr>
                        <td>{{$sl++}}</td>
                        <td>{{$category['name']}}</td>
                        <td>
                            @if($category->publication_status==1)
                                <span class="fa fa-thumbs-o-up text-success">publish</span>
                            @else
                                <span class="fa fa-thumbs-o-down text-danger">un publish</span>
                            @endif

                        </td>
                        <td>
                            @if($category->publication_status==1)
                                <a class="btn btn-success" href="{{asset('unpublished-category/'.$category->id)}}"
                                   style="float: left;margin-right: 3px;">
                                    <i class="glyphicon glyphicon-thumbs-down"></i>
                                </a>
                            @else
                                <a class="btn btn-danger" href="{{asset('published-category/'.$category->id)}}"
                                   style="float: left;margin-right: 3px;">
                                    <i class="glyphicon glyphicon-thumbs-up"></i>
                                </a>
                            @endif
                            {!! Html::decode(Html::linkRoute('category.show','<i class="fa fa-eye">view</i>', [$category->id],['style'=>'margin:5px; float:left'])) !!}
                            {!! Html::decode(Html::linkRoute('category.edit','<i class="fa fa-pencil-square-o">edit</i>', [$category->id],['style'=>'margin:5px; float:left'])) !!}
                            {!! Form::open(['route'=>['category.destroy',$category->id],'method'=>'DELETE']) !!}
                            {{  Form::button( '<i class="fa fa-trash-o"></i>', ['type' => 'submit','style'=>'margin:0;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
                            {!! Form::close() !!}
                        </td>

                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection