routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/','WelcomeController@index');
Route::get('/single/{id}','SingleController@show');
Route::get('/cat/{id}','PagesController@show');

//Route::get('/single', function () {
//    return view('pages.single');
//});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/home', 'HomeController@index')->name('home');

// manage category
Route::get('published-category/{id}','CategoriesController@publish_category');
Route::get('unpublished-category/{id}','CategoriesController@unpublish_category');
Route::resource('category','CategoriesController');

// manage slider
Route::get('published-slider/{id}','SlidersController@publish_slider');
Route::get('unpublished-slider/{id}','SlidersController@unpublish_slider');
Route::resource('slider','SlidersController');

// manage category
Route::get('published-product/{id}','ProductsController@publish_product');
Route::get('unpublished-product/{id}','ProductsController@unpublish_product');
Route::resource('product','ProductsController');
// manage location
Route::get('published-location/{id}','LocationsController@publish_location');
Route::get('unpublished-location/{id}','LocationsController@unpublish_location');
Route::resource('location','LocationsController');
Route::resource('seller','SellersController');

app/Seller.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Seller extends Model
{
//    public function products()
//    {
//        return $this->belongsToMany(Product::class);
//    }
    public function location()
    {
        return $this->belongsTo('App\Location');
    }
}

app/Http/Controllers/SellersController.php
<?php

namespace App\Http\Controllers;

use App\Seller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Location;

class SellersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $sellers=Seller::all();
       return view('sellers.index')->withSellers($sellers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $locations = Location::all();
       return view('sellers.create')->withLocations($locations);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',
            'phone'=>'required',
            'location_id'=>'required',
            'publication_status'=>'required'

        ]);

        $seller=new Seller();
        $seller->name=$request->name;
        $seller->phone=$request->phone;
        $seller->location_id=$request->location_id;
        $seller->publication_status=$request->publication_status;
        $seller->save();

        Session::flash('message','Seller Insert Successfully');
        return redirect()->route('seller.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public  function __construct()
    {
        $this->middleware('auth');
    }

    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $seller=Seller::findOrFail($id);
        $locations=Location::all();
        return view('sellers.edit')->withSeller($seller)->withLocations($locations);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required',
            'phone'=>'required',
            'location_id'=>'required',
            'publication_status'=>'required'
        ]);

        $seller=Seller::findOrFail($id);
        $seller->name=$request->name;
        $seller->phone=$request->phone;
        $seller->location_id=$request->location_id;
        $seller->publication_status=$request->publication_status;
        $seller->update();

        Session::flash('message','Seller Update Successfully');
        return redirect()->route('seller.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $seller=Seller::findOrFail($id);
        $seller->delete();
        Session::flash('message','Seller Deleted Successfully');
        return redirect()->route('seller.index');
    }
}

resources/views/sellers/create.blade.php
@extends('admin.master')
@section('main-content')
    <div class="well">
        <h3>Create Seller</h3>
        @if($errors->all())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors as $error)
                        <li>{{$error->error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if(Session::get('message'))
            <div class="alert alert-success">
                <h4>{{Session::get('message')}}</h4>
            </div>
        @endif
        <form action="{{route('seller.store')}}" method="post">
            {{csrf_field()}}
            <div class="form-group">
                <label for="name">Seller Name</label>
                <input type="text" name="name" class="form-control">
            </div>
            <div class="form-group">
                <label for="phone">Phone No: </label>
                <input type="number" name="phone" class="form-control">
            </div>
            <div class="form-group">
                <label for="location">Select Location</label>
                <select name="location_id" id="location" class="form-control">

                    @foreach($locations as $location)
                        <option value="{{$location->id}}">{{$location->address}}</option>
                    @endforeach
                </select>
            </div>
            <label for="publication_status">Publication Status:</label>
            <select name="publication_status" id="" class="form-control">
                <option value="1">Publish</option>
                <option value="0">Un Publish</option>
            </select>
            <br>
            <input type="submit" value="Save" class="btn btn-success">
        </form>
    </div>

@endsection

resources/views/sellers/edit.blade.php
@extends('admin.master')
@section('main-content')
    <div class="panel panel-default">

        <div class="panel-heading"><i class="fa fa-laptop"> EDIT SELLER </i></div>
        @if($errors->all())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors as $error)
                        <li>{{$error->error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if(Session::get('message'))
            <div class="alert alert-success">
                <h4>{{Session::get('message')}}</h4>
            </div>
        @endif
        <div class="panel-body">
            {!! Form::model($seller,['route'=>['seller.update',$seller->id],'method' => 'patch']) !!}

            <div class="form-group">
                {{Form::label('name','Name:')}}
                {{Form::text('name',null,['class'=>'form-control'])}}
            </div>

            <div class="form-group">
                {{Form::label('phone','Phone:')}}
                {{Form::number('phone',null,['class'=>'form-control'])}}
            </div>
            <div class="form-group">
                <label for="location">Location</label>
                <select id="location"
                        name="location_id"
                        class="form-control">
                    @foreach($locations as $location)
                        @if ($location->id == $seller->location_id)
                            <option selected
                                    value="{{$location->id}}">{{$location->address}}</option>
                        @else
                            <option value="{{$location->id}}">{{$location->address}}</option>
                        @endif
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                {{ Form::select('publication_status', ['1' => 'Publish', '0' => 'Un Publish'], null, ['placeholder'=>'select status', 'class' => 'form-control'])}}

            </div>
            {{Form::submit('update',['class'=>'btn btn-success btn-sm'])}}
            {!! Form::close() !!}
            <a href="{{route('seller.index')}}" class="fa fa-arrow-left btn btn-info btn-sm"> back</a>
            {!! Form::open(['route'=>['seller.destroy',$seller->id],'method'=>'DELETE']) !!}
            {{  Form::button( '<i class="fa fa-trash-o">delete</i>', ['type' => 'submit','class'=>'btn btn-danger btn-sm','style'=>'margin:0;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/sellers/index.blade.php
@extends('admin.master')
@section('main-content')

        <div class="well">
            <h3><a href="{{route('seller.create')}}">ADD NEW + </a>SELLER</h3>

            <form action="{{route('seller.index')}}" method="get" class="pull-right form-inline">
                <div class="form-group">
                    <input type="text" role="search" class="form-control">
                    <input type="submit" value="search" class="btn btn-info">
                </div>
            </form>

            <table class="table">
                <thead>
                <tr>
                    <th>SL</th>
                    <th>NAME</th>
                    <th>PHONE</th>
                    <th>PUBLICATION STATUS</th>
                    <th>ACTION</th>
                </tr>
                </thead>
                <tbody>
                @php($sl=1)
                @foreach($sellers as $seller)
                    <tr>
                        <td>{{$sl++}}</td>
                        <td>{{$seller['name']}}</td>
                        <td>{{$seller['phone']}}</td>
                        <td>
                            @if($seller->publication_status==1)
                                <span class="fa fa-thumbs-o-up text-success">publish</span>
                            @else
                                <span class="fa fa-thumbs-o-down text-danger">un publish</span>
                            @endif

                        </td>
                        <td>
                            {!! Html::decode(Html::linkRoute('seller.show','<i class="fa fa-eye">view</i>', [$seller->id],['style'=>'margin:5px; float:left'])) !!}
                            {!! Html::decode(Html::linkRoute('seller.edit','<i class="fa fa-pencil-square-o">edit</i>', [$seller->id],['style'=>'margin:5px; float:left'])) !!}
                            {!! Form::open(['route'=>['seller.destroy',$seller->id],'method'=>'DELETE']) !!}
                            {{  Form::button( '<i class="fa fa-trash-o"></i>', ['type' => 'submit','style'=>'margin:0;','onclick'=>'return confirm("Are You Sure You Want To Delete This! ")'])}}
                            {!! Form::close() !!}
                        </td>

                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>


@endsection